[project]
name = "yolo-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.50.0",
    "streamlit-webrtc>=0.63.11",
    "ultralytics>=8.3.221",
]
